language: python

# Run on container-based infrastructure
sudo: false

python:
  - "2.6" # ST2

env:
  # Do not do speed tests since they won't work and would generate a failure
  - TINYCSS_SKIP_SPEEDUPS_TESTS

install:
  - pip install -r dev-requirements.txt

script:
  - flake8 -v .
  # Run tinycss and tinycsscheme tests
  - >-
    py.test tinycsscheme/tests/
    --cov tinycsscheme
    --cov-config tinycsscheme/.coveragerc
    --cov-report term-missing

after_success:
  - coveralls
